C     *==========================================================*
C     | POLLUTANT_SIZE.h
C     | o Ocean Pollutant Package Size Definitions
C     *==========================================================*

C     POLLUTANT_SIZE.h is automatically generated by genmake2
C     DO NOT EDIT

C     Maximum number of pollutant tracers
      INTEGER     POLLUTANT_num
      PARAMETER ( POLLUTANT_num = 1 )

C     Number of pollutant tracers
      INTEGER     POLLUTANT_Tr_num
      PARAMETER ( POLLUTANT_Tr_num = 1 )

C     Pollutant tracer index
C     POLLUTANT_pTr_i1 :: pTracer index of first POLLUTANT tracer
      COMMON /POLLUTANT_INDEX/ POLLUTANT_pTr_i1
      INTEGER POLLUTANT_pTr_i1

C     Maximum number of pollutant diagnostics
      INTEGER     POLLUTANT_numDiag
      PARAMETER ( POLLUTANT_numDiag = 6 )